
export const userConstants = {

  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",


  USER_LOGOUT_REQUEST :"USER_LOGOUT_REQUEST",
  USER_LOGOUT_SUCCESS : "USER_LOGOUT_SUCCESS",

  PROFILE_UPDATE_REQUEST : "PROFILE_UPDATE_REQUEST",
  PROFILE_UPDATE_SUCCESS : "PROFILE_UPDATE_SUCCESS",
  PROFILE_UPDATE_FAILURE : "PROFILE_UPDATE_FAILURE"
}
export const categoryConstants = {
  GET_Category_REQUEST : "GET_Category_REQUEST",
  GET_Category_SUCCESS : "GET_Category_SUCCESS",
  GET_Category_FAILURE : "GET_Category_FAILURE",

  ADD_Category_REQUEST : "ADD_Category_REQUEST",
  ADD_Category_SUCCESS : "ADD_Category_SUCCESS",
  ADD_Category_FAILURE : "ADD_Category_FAILURE",

  EDIT_Category_REQUEST : "EDIT_Category_REQUEST",
  EDIT_Category_SUCCESS : "EDIT_Category_SUCCESS",
  EDIT_Category_FAILURE : "EDIT_Category_FAILURE",

  DELETE_Category_REQUEST : "DELETE_Category_REQUEST",
  DELETE_Category_SUCCESS : "DELETE_Category_SUCCESS",
  DELETE_Category_FAILURE : "DELETE_Category_FAILURE",


};

export const bookConstants ={
  GET_BOOK_LIST_REQUEST : "GET_BOOK_LIST_REQUEST",
  GET_BOOK_LIST_SUCCESS : "GET_BOOK_LIST_SUCCESS",
  GET_BOOK_LIST_FAILURE : "GET_BOOK_LIST_FAILURE",

}
export const reviewConstant ={
  GET_REVIEWS_REQUEST : "GET_REVIEWS_REQUEST",
  GET_REVIEWS_SUCCESS : "GET_REVIEWS_SUCCESS",
  GET_REVIEWS_FAILURE : "GET_REVIEWS_FAILURE",

}
